### ISSUE TITLE
The settings window and tray menu are occasionally shown in light mode even though the dark theme is selected.

### ISSUE THREAD

**Issue by tschroedter** [tschroedter/idasen-desk#41]
The settings window and tray menu are occasionally shown in light mode even though the dark theme is selected.
When this is happening, the "Dark" option is shown as selected and clicking on it again solves the problem.
I use the dark mode and hibernate the computer, so when I power the computer on again the program is already running but it's shown in light mode instead. However, it has happened a couple of times only and I couldn't find a way to reproduce it.

**Comment by tschroedter** [comment]
This has been already fixed but not release. It will be in the next release after v0.1.182. 

The fix uses a different way to detect the current windows them. 
More infos here:
- [Know when dark mode is enabled](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes?WT.mc_id=DT-MVP-5003978#know-when-dark-mode-is-enabled)
- [High contrast](https://engy.us/blog/2018/10/20/dark-theme-in-wpf/#:~:text=We%E2%80%99ll%20need%20to%20find%20if%20High%20Contrast%20is,a%20value%20from%20this%20enum%3A%20Light%2C%20Dark%2C%20HighContrast) (not detected at the moment)

**Comment by tschroedter** [comment]
I'll have another look when I have some time. 

First thoughts:
- I haven't seen it changing themes when it's running. - Usually, I close the UI, maybe I have to keep it open and see if it changes themes.
- I usually don't use hibernation. - So, I have to enable it and try it.
- Maybe, there is a problem when saving the theme? Maybe, it's not saved correctly?

@Glakt Can you try to reset your settings and see if it fixes your problem? - There is an option under the 'Advanced' expander saying 'Settings' and a button 'Reset All'.

**Comment by Glakt** [comment]
Sure, I'm going to reset all settings and test the program thoroughly again.

I'll let you know about my findings.

**Comment by Glakt** [comment]
Hi Tom,

I'm reporting back after testing v0.1.299 for the last few days.

It took me a bit longer than expected because I had to do further tests while findings were popping up.

Unfortunately, the settings reset didn't solve the issue. The program is still reverting to the light mode, sometimes after resuming from hibernation and sometimes during the Windows session. It generally happens once or twice daily.

I also deleted the folder `C:\ProgramData\Idasen.SystemTray` and all the program version folders in `C:\Users\Username\AppData\Local\Temp\.net` to test a "clean" v0.1.299, but it didn't bring any change either. I didn't delete any registry entry from previous versions, although I can do it if you think it might be worth it to explore a potential conflict with older versions.

> Maybe, there is a problem when saving the theme? Maybe, it's not saved correctly?

I had this thought too, so I did some additional checks:

1. I had a look at the file `settings.json` and it seems the dark theme is correctly saved, as you can see below:

```
{"deviceSettings":{"deviceName":"Desk","deviceAddress":250635178951455,"deviceMonitoringTimeout":600,"deviceLocked":false,"notificationsEnabled":true,"stopIsVisibleInContextMenu":true,"maxSpeedToStopMovement":40},"heightSettings":{"standingHeightInCm":96,"seatingHeightInCm":68,"custom1HeightInCm":115,"custom2HeightInCm":74,"deskMinHeightInCm":60,"deskMaxHeightInCm":127,"lastKnownDeskHeight":68,"standingIsVisibleInContextMenu":true,"seatingIsVisibleInContextMenu":true,"custom1IsVisibleInContextMenu":true,"custom2IsVisibleInContextMenu":true},"appearanceSettings":{"themeName":"Dark"}}
```

2. I inspected the file `Idasen.SystemTray.log` and found entries related to a `Failed to load settings` error:

```
2025-11-01 14:25:52.626 +01:00 [Error] (pid:4444 tid:1 caller:Idasen.SystemTray.Win11.Utils.SettingsSynchronizer) Failed to load settings
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.DependencyObject.SetCurrentValue(DependencyProperty dp, Object value)
   at Wpf.Ui.Appearance.ApplicationThemeManager.Apply(ApplicationTheme applicationTheme, WindowBackdropType backgroundEffect, Boolean updateAccent)
   at Idasen.SystemTray.Win11.Utils.SettingsSynchronizer.LoadSettingsAsync(ISettingsViewModel model, CancellationToken token)
2025-11-01 14:25:52.708 +01:00 [Error] (pid:4444 tid:1 caller:) Failed to start application
System.InvalidOperationException: Failed to load settings
   at Idasen.SystemTray.Win11.Utils.SettingsSynchronizer.LoadSettingsAsync(ISettingsViewModel model, CancellationToken token)
   at Idasen.SystemTray.Win11.ViewModels.Pages.SettingsViewModel.InitializeAsync(CancellationToken token)
   at Idasen.SystemTray.Win11.App.HandleInitializingApplication()
   at Idasen.SystemTray.Win11.App.OnStartup(Object sender, StartupEventArgs args)
```

The error entries were only logged the first day of testing, while the light/dark theme issue kept happening for the next few days.

I did further tests to try to collect more hints about the issue and found out interesting things:

3. The `Log Folder` and `Settings File` path fields in advanced settings become empty when I change to the dark theme, close (exit) the program and launch it again (see the screenshot below). The paths won't be shown anymore (even relaunching the program many times) unless I select the light theme, close (exit) the program and launch it again. This behavior is reproduced every time I follow the steps above.

<img width="780" height="780" alt="Image" src="https://github.com/user-attachments/assets/d618bd53-8197-499d-aeca-799a8a07d2c4" />

4. The `Failed to load settings` error entries in point 2 are actually logged every time the program is relaunched in dark mode (no additional errors are logged afterwards if the program keeps running for days). However, there are no error entries at all if the light theme is selected and the `Log Folder` and `Settings File` paths are visible, no matter how many times the program is relaunched.

5. Setting changes aren't saved immediately after the dark theme is selected and the program is closed and relaunched. In this case, they are only saved after switching to another tab in the settings window. However, if the light theme is selected and the program is closed and relaunched, changes will be saved immediately. Interestingly, they will also be saved immediately if the dark theme is selected but the program isn't closed and relaunched, but the issue will happen again the moment the computer is shut down and powered on again, as the program will be closed and relaunched consequently.

6. Expanding on points 3 and 5, when the dark theme is selected and the program isn't closed and relaunched, the `Log Folder` and `Settings File` paths remain visible. Since the setting changes were saved immediately (as intended) in this case, I further tested whether the light/dark theme issue was also solved in this particular scenario. However, I'm afraid the program is still reverting to the light mode.

7. I didn't notice any problem with my custom desk positions while testing the program, as the desk did move to the right positions.

It seems the program might have some kind of problem getting access to the settings file, as suggested by the error `Failed to load settings`. However, the connection between the error and the light/dark theme issue isn't completely clear, taking into account all the results.

Hopefully these findings are useful and help you figure out what's happening.

**Comment by tschroedter** [comment]
Re-opening the issue, because it got closed before testing the changes.

**Comment by tschroedter** [comment]
Hi @Glakt,

I've created a new release v0.1.329 which hopefully fixes the issue. 

Can you quickly test it?
- Do you still get the 'Failed to load settings' error?
- Does applying the theme work?

Thanks,
Tom

**Comment by Glakt** [comment]
Unfortunately, the program is still reverting to the light mode.

The warning lines below have also been logged with v0.1.329 and older versions, so I'm wondering if they could have something to do with the issue: 

```
[Warning] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Core.ServicesDiscovery.Wrappers.GattCharacteristicValueChangedObservables) Access denied - Bluetooth is probably disabled ("Attempted to perform an unauthorized operation.")
[Information] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.DeskConnector) ["BluetoothLE#BluetoothLEf0:a6:54:8a:5d:98-d9:18:79:6b:3c:9c"] ConnectionStatus=Connected GattCommunicationStatus=Success DeviceGattStatus=Success
[Warning] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Characteristics.Common.RawValueReader) GattCharacteristic 99fa0021-338a-1024-8a49-009c0215f78a doesn't support "Read" but supports "Notify"
[Warning] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Characteristics.Common.RawValueReader) GattCharacteristic 99fa0011-338a-1024-8a49-009c0215f78a doesn't support "Read" but supports "Notify"
[Warning] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Characteristics.Common.RawValueReader) GattCharacteristic 99fa0003-338a-1024-8a49-009c0215f78a doesn't support "Read" but supports "Notify"
[Warning] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.RawValueToHeightAndSpeedConverter) Failed to convert raw value "" to height and speed. Payload too short (0)
[Information] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.DeskProvider) Detected desk "Desk XXXX" with Bluetooth address "***13500"
[Information] (pid:6640 tid:1 caller:Idasen.SystemTray.Win11.Utils.UiDeskManager) Executing "SitAsync" which moves the desk to height 69 cm...
[Information] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.Control.InitialHeightProvider) Trying to determine current height by moving the desk
[Information] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.Control.InitialHeightProvider) Received valid height 7462
[Information] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.Control.DeskMover) Reached target height=6886
```
Let me know if I can help you with anything else.

**Comment by tschroedter** [comment]
You can ignore these warnings, they are part of the desk discovery process. With Bluetooth you have to do some try and error when detecting a device.  - Maybe, I should only log them as debug or information.

It would be great if you zip and attach the complete log file.

_PS: If the log file doesn't help, I will tell you how to enable debug logging and ask you to test again._

**Comment by tschroedter** [comment]
I can see the switch in the log:

_2025-11-11 09:10:26.664 +01:00 [Information] (pid:6640 tid:1 caller:Idasen.SystemTray.Win11.Utils.UiDeskManager) Executing "SitAsync" which moves the desk to height 69 cm...
2025-11-11 09:10:26.664 +01:00 [Information] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.Control.InitialHeightProvider) Current height is 6796
2025-11-11 09:10:27.271 +01:00 [Information] (pid:6640 tid:1 caller:Idasen.BluetoothLE.Linak.Control.DeskMover) Reached target height=6901
2025-11-11 09:10:36.333 +01:00 [Information] (pid:6640 tid:1 caller:Idasen.SystemTray.Win11.Utils.MyApplicationThemeManager)_ **Successfully applied theme 'Light'...**
_2025-11-11 09:10:38.523 +01:00 [Information] (pid:6640 tid:1 caller:Idasen.SystemTray.Win11.Utils.MyApplicationThemeManager)_ **Successfully applied theme 'Dark'...**
_2025-11-11 09:22:39.597 +01:00 [Information] (pid:6640 tid:1 caller:Idasen.SystemTray.Win11.Utils.UiDeskManager) Executing "SitAsync" which moves the desk to height 69 cm..._

But it doesn't show how it was triggered... so debug logging it is :)

Can you....
- Stop the app.
- Copy and past the 'appsettings.json' file into the same folder as the 'Idasen-SystemTray-0.1.329-win-x64.exe' file
[appsettings.json](https://github.com/user-attachments/files/23475800/appsettings.json)
- Start the app.
- Check the log file, you should see lots of debug messages in the log file.
- Use the app until it changes the them by itself again.
- Zip the log file and attached to this issue.

Thanks for your help!

**Comment by Glakt** [comment]
Hi Tom,

This time the program has switched to the light theme by itself during the Windows session.

The complete debug log file is attached (password: "Idasen").

[Idasen.SystemTray debug.zip](https://github.com/user-attachments/files/23496995/Idasen.SystemTray.debug.zip)

I have also checked the log file and it seems it doesn't show how it was triggered, so I detail below the chronology of events to make it easier for you:

- 08:58: I opened the tray menu after resuming the computer from hibernation and it was in dark mode.
             I then selected the "Sit" position and the desk moved to the right position.
- 09:07: I opened the tray menu to check if it was in dark mode and everything was fine.
- 10:14: I opened the tray menu again to check if it was in dark mode and this time it was shown in light mode.

The `settings.json` file content after the event is shown below:

```
{"deviceSettings":{"deviceName":"Desk","deviceAddress":250635178951455,"deviceMonitoringTimeout":600,"deviceLocked":false,"notificationsEnabled":true,"stopIsVisibleInContextMenu":true,"maxSpeedToStopMovement":40},"heightSettings":{"standingHeightInCm":96,"seatingHeightInCm":69,"custom1HeightInCm":74,"custom2HeightInCm":74,"deskMinHeightInCm":60,"deskMaxHeightInCm":127,"lastKnownDeskHeight":69,"standingIsVisibleInContextMenu":true,"seatingIsVisibleInContextMenu":true,"custom1IsVisibleInContextMenu":true,"custom2IsVisibleInContextMenu":true},"appearanceSettings":{"themeName":"Dark"}}
```

Hopefully there is something else to help you figure out what's happening.

**Comment by Glakt** [comment]
Hi Tom,

Good news! The program hasn't switched to the light mode since I started testing v0.1.336, so it seems the issue is fixed in the new version. Thank you so much!

FYI, my setup is a laptop with an APU, so no dedicated GPU or eGPU on my end.

Regards,
Glakt
